# Generated by Django 4.0.5 on 2022-06-11 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('objective', models.CharField(max_length=255)),
                ('projects', models.TextField()),
                ('skills', models.CharField(max_length=255)),
                ('location', models.TextField()),
                ('regards', models.CharField(max_length=255)),
                ('tempdata', models.CharField(choices=[('template1', 'template1'), ('template2', 'template2')], max_length=200)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
